# Generated by Django 3.2.8 on 2021-10-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='varition_category',
            new_name='variation_category',
        ),
    ]
